version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_car_wash_service
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=service_db
